language: node_js
node_js:
  - "lts/*"
install:
  - npm
script:
  - npm run test
  - npm run cover
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
